version: '3.8'
services:
   web:
       build: .
       command: bash -c "
            python -m src.preprocess &&
            python -m src.train &&
            python -m src.predict &&
            coverage run -m src.unit_tests.test_preprocess &&
            coverage run -a -m src.unit_tests.test_training &&
            coverage report -m &&
            python -m main
        "
       ports:
           - 8000:8000
       image: nikita123orange/devops-laba1:latest